name: CI

on:
  # push:
  #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: trigger remote deploy
        run: |
          cd ${{ github.workspace }}
          echo "${{ secrets.SSH_KEY }}" > .ssh_id
          chmod 400 .ssh_id
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} -i .ssh_id "bash -s" < ./deploy.sh
