name: CI

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: trigger remote deploy
        run: |
          echo "${{ secrets.SSH_KEY }}" > .ssh_id
          ssh root@${{ secrets.SSH_HOST }} -i .ssh_id 'curl -s https://raw.githubusercontent.com/sid093/whatsviz/master/deploy.sh | bash /dev/stdin'
